version: '3.3'
services:
  db:
    image: delivery-sql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    expose:
      - '3306'
  delivery:
    image: delivery
    ports:
      - '8080:8080'
